# Generated by Django 3.0.4 on 2020-03-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
            preserve_default=False,
        ),
    ]
