# Generated by Django 3.0.4 on 2020-03-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200315_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_bool',
            field=models.BooleanField(),
        ),
    ]
