# Generated by Django 3.0.4 on 2020-03-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200315_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
