# Generated by Django 3.0.4 on 2020-03-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200315_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_bool',
            field=models.BooleanField(default=False),
        ),
    ]
